name: tridev_common_test
version: 1.0.0
homepage: https://github.com/tridev-dart/common-test
description: A collection of classes and function used for testing tridev and by the tridev test harness.
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  tridev: ^1.0.0
  tridev_common: ^1.0.0