name: tridev_common
version: 1.0.0
description: Common classes shared by tridev projects.
repository: https://github.com/bsutton/tridev-orm
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  tridev_open_api: ^1.0.0
dev_dependencies: 
  lint: ^1.0.0
