name: tridev
version: 3.2.3
homepage: https://github.com/tridev-dart/tridev
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  args: ^2.1.1
  analyzer: ^1.3.0
  collection: ^1.15.0
  tridev_common: ^1.0.0
  tridev_config: ^1.0.0
  tridev_isolate_exec: ^1.0.0
  tridev_open_api: ^1.0.0
  tridev_security_hash: ^1.0.0
  tridev_runtime: ^1.0.0
  crypto: ^3.0.0
  logging: ^1.0.0
  meta: ^1.1.5
  path: ^1.6.1
  postgres: ^2.3.1
  pub_cache: ^0.3.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0
dev_dependencies:
  http: ^0.13.0
  matcher: ">=0.12.3 <0.14.0"
  mockito: ^5.0.0
  pedantic: ^1.0.0
  test: ^1.16.5
  tridev_fs_agent:
    path: ../tridev_fs_agent
  # tridev_common_test:
  #   path: ../common_test
  tridev_test:
    path: ../test_harness
  web_socket_channel: ^2.2.0
executables:
  tridev: tridev
