version: "3.3"
   
services:
  postgres:
    image: postgres:11
    # command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    container_name: tridev_postgres
    restart: always
    environment:
      POSTGRES_USER: tridev_test_user
      POSTGRES_PASSWORD: tridev!
      POSTGRES_DB: tridev_test_db
      POSTGRES_PORT: 15432
    ports:
      - 0.0.0.0:15432:5432
    volumes:
    - ./ssl/server.crt:/var/lib/postgresql/server.crt:ro
    - ./ssl/server.key:/var/lib/postgresql/server.key:ro
