name: tridev_security_hash
version: 1.0.0
homepage: https://github.com/tridev/dart-password-hash
description: PBKDF2 security hashing utility
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  crypto: ^3.0.0
dev_dependencies: 
  lint: ^1.5.0
  test: ^1.16.5
