name: wildfire
description: An empty tridev application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  tridev: ^1.0.1

dev_dependencies:
  test: ^1.21.6
  tridev_test: ^1.0.0
