name: wildfire
description: An empty tridev application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  tridev: ^1.0.0

dev_dependencies:
  test: ^1.16.5
  tridev_test: ^3.2.0
