name: tridev_config
version: 1.0.0
description: A safe and convenient way to read YAML configuration files.
repository: https://github.com/tridev-dart/tridev-config.git
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  tridev_runtime: ^1.0.0
  meta: ^1.3.0
  yaml: ^3.1.0
dev_dependencies: 
  lint: ^1.5.0
  test: ^1.16.5
