name: tridev_open_api
version: 1.0.1
homepage: https://github.com/tridev/open-api-dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  tridev_codeunit: ^1.0.1
  meta: ^1.8.0
dev_dependencies: 
  lint: ^1.10.0
  test: ^1.21.6
